check50:
  dependencies:
    - "jupyter"
    - "pandas"
  files:
    - !exclude "*"
    - !require "module 2.ipynb"
    - !require "answers.py"
    - !require "mini-movielens"
    - !require "micro-movielens"
